/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#80d5ff',
        'on-primary': '#003d5c',
        'primary-container': '#005580',
        'on-primary-container': '#b3e9ff',
        'secondary': '#b0cfe0',
        'on-secondary': '#1d3a47',
        'secondary-container': '#34515f',
        'on-secondary-container': '#cceafc',
        'tertiary': '#c7d2e4',
        'on-tertiary': '#2e2f42',
        'tertiary-container': '#454759',
        'on-tertiary-container': '#e4efff',
        'error': '#f2b8b5',
        'on-error': '#601410',
        'error-container': '#8c1d18',
        'on-error-container': '#ffdad6',
        'surface': '#0f1419',
        'surface-bright': '#353a42',
        'surface-container-lowest': '#0a0e13',
        'surface-container-low': '#161b22',
        'surface-container': '#1a202a',
        'surface-container-high': '#242d39',
        'surface-container-highest': '#2f3844',
        'on-surface': '#e2e1e6',
        'on-surface-variant': '#c7c6d0',
        'outline': '#91909a',
        'outline-variant': '#49484f',
        'scrim': '#000000',
        'success': '#10b981',
        'info': '#06b6d4',
        'warning': '#f59e0b',
      },
    },
  },
  plugins: [],
}