# Generated by Django 5.1.2 on 2026-04-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('status', models.CharField()),
            ],
        ),
    ]
