# Generated by Django 6.0.4 on 2026-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binis_invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_full', models.CharField(max_length=30)),
                ('brand_display', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='price',
        ),
    ]
