# Generated by Django 6.0.4 on 2026-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binis_invoices', '0002_brand_rename_status_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_full',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
